// lib/constants/routes.ts
export const routes = {
  home: "/",
  products: "/products",
  product: (id: string) => `/products/${id}`,
  categories: "/categories",
  category: (slug: string) => `/categories/${slug}`,
  collections: "/collections",
  collection: (slug: string) => `/collections/${slug}`,
  search: "/search",
  wishlist: "/wishlist",
  cart: "/cart",
  checkout: "/checkout",
  checkoutShipping: "/checkout/shipping",
  checkoutPayment: "/checkout/payment",
  checkoutConfirmation: "/checkout/confirmation",
  account: "/account",
  orders: "/account/orders",
  order: (id: string) => `/account/orders/${id}`,
  profile: "/account/profile",
  about: "/about",
  contact: "/contact",
  privacyPolicy: "/policies/privacy",
  termsOfService: "/policies/terms",
  shippingPolicy: "/policies/shipping",
};
